// Custom root HTML for the web/PWA export (expo-router). Wraps every page server-side.
// This is where we inject the install/PWA <head> tags Expo's default HTML doesn't emit:
// the web app manifest, the Apple touch icon (which iOS — not the manifest — uses for
// "Add to Home Screen"), theme colour, and the apple-mobile-web-app-* meta. The tab
// favicon is still injected automatically from `web.favicon` in app.json, so it's not here.
// Icons + manifest live in apps/mobile/public (generated by scripts/gen-icons.mjs).
// NOTE: standalone status-bar style + safe-area handling still need on-device verification.
import { ScrollViewStyleReset } from 'expo-router/html'
import type { PropsWithChildren } from 'react'

export default function Root({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

        {/* Installable PWA */}
        <link rel="manifest" href="/manifest.webmanifest" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <meta name="theme-color" content="#111827" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="apple-mobile-web-app-title" content="NextBus HK" />

        {/*
          Disable body scrolling on web so ScrollView primitives own scrolling.
          Must be after the viewport meta (see expo-router docs).
        */}
        <ScrollViewStyleReset />
      </head>
      <body>{children}</body>
    </html>
  )
}
