#!/usr/bin/env node
/**
 * The SPA deep-link fallback for the **host** — one declaration, two consumers, for exactly the reason
 * `workbox.config.mjs` beside it is one (ADR-058, ADR-082).
 *
 *   node scripts/pwa/redirects.mjs <distDir>
 *
 * ## Why this is not a file in `public/`
 *
 * It was, in `apps/web/public/_redirects`, and that was wrong in the way ADR-082 already ruled on. The
 * service worker's `navigateFallback` and this rewrite are **the same decision** — *an unknown deep path
 * opens the app, at the path that was shared* — answered on the two sides of the same round trip: the
 * worker covers every visit after the first, and only the host can cover the first. ADR-082 made the
 * caching policy shared precisely so two PWAs could not disagree about what a rider sees with no network;
 * a hand-copied `_redirects` in one app's `public/` reintroduces that split one layer down, and it did:
 * `apps/mobile` — **the PWA that actually ships today**, WP0-5 — had no copy and 404'd on the same link.
 *
 * So the rule lives here, next to the `navigateFallback` it mirrors, and takes its target from it: both
 * apps' `build:web` run this file over their `dist/`. `apps/web/test/pwa-policy.test.mjs` asserts the
 * declaration and that both `build:web` scripts still run it; `writeRedirects` below asserts the artefact
 * at build time. Same two places, same reasons, as the worker's own claims.
 *
 * ## Why it is written *after* the exporter and the service worker
 *
 * `build:web` deletes `dist/`, exports, then generates `sw.js` over the result — so this runs last, and
 * the file cannot end up in the precache manifest even by accident. (It could not anyway: the globs are
 * extension-qualified and `_redirects` has no extension. Both facts are asserted; the order is the one
 * that survives someone adding `**\/*` to the globs.)
 *
 * Neither caller is a turbo task, so ADR-070 does not bite — the same footnote `workbox.config.mjs`
 * carries, and for the same reason: a `build:web` promoted into `turbo.json` must declare this path in
 * `inputs`.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { NAVIGATE_FALLBACK } from './workbox.config.mjs'

/** The filename Cloudflare Pages, Netlify and Workers static assets all read at deploy time. */
export const REDIRECTS_FILE = '_redirects'

/**
 * The rule. `200` is a **rewrite**, not a redirect, and the target is the worker's own `navigateFallback`
 * rather than a second `/index.html` written out here — the two must not be able to disagree.
 */
export const SPA_FALLBACK_RULE = `/*    ${NAVIGATE_FALLBACK}    200`

/**
 * The emitted file, comments and all. The rationale ships *in the artefact* because the artefact is what
 * someone debugging a 404 on a live host will open first, and a host that does not read `_redirects` just
 * serves it as an unused text file.
 */
export const REDIRECTS = `# The SPA fallback for a **first** visit to a deep link — the half a service worker cannot cover.
#
# GENERATED by \`scripts/pwa/redirects.mjs\`, which both apps' \`build:web\` run. Edit it there, not here:
# one declaration, because this is the host-side half of the worker's \`navigateFallback\` and two copies
# could disagree about what a rider sees (ADR-082).
#
# \`scripts/pwa/workbox.config.mjs\` sets \`navigateFallback: '${NAVIGATE_FALLBACK}'\`, and that is what makes
# \`/route/KMB%3A1%2Foutbound%2F1\` open the app **offline** and on every later visit. It only applies once the
# worker is installed. The first visit — the one that arrives from a message a rider was sent, which is the
# whole point of a shareable URL — goes to the origin, where there is no \`route/…\` file to serve. Neither
# build has one: \`vite build\` emits a single HTML entry, and Expo's static export emits one per *route*, so
# the dynamic ones land as \`route/[id].html\` — a filename with brackets in it that no host matches to
# \`/route/KMB:1\`. Without this line that rider gets the host's 404 page and concludes the link is broken.
#
# \`200\`, not \`301\`/\`302\`: a rewrite, so the address bar keeps the path the client-side router has to read
# (react-router in \`apps/web\`, expo-router in \`apps/mobile\`). A redirect to \`/\` would open the app at Nearby
# and silently drop the place, route or query that was shared, which is the more confusing failure of the two.
#
# Static assets win over this rule — Cloudflare Pages, Netlify and Workers static assets all match a real
# file first — so \`/assets/index-<hash>.js\`, \`/sw.js\`, \`/manifest.webmanifest\` and the icons are served as
# themselves, and Expo's pre-rendered \`/search\` and \`/faq\` are served as their own pages rather than through
# the fallback. The API is a **different origin** (\`DEFAULT_API_URL\` in \`@nextbus/api-client\`), so no
# \`/v1/…\` request is ever answered by this file; that is the same statement the worker's
# \`navigateFallbackDenylist\` makes on the client side. If the API is ever put behind this origin, it needs a
# rule above this one.
#
# Inert until there is a host (WP0-5 is not done). It is written after \`generateSW\`, and it has no file
# extension while every precache glob is extension-qualified, so it is in neither app's precache manifest
# and changes not one byte of \`sw.js\`.

${SPA_FALLBACK_RULE}
`

/**
 * Write `_redirects` into a finished build, and check the two things that make it worth writing.
 *
 * Asserted rather than assumed, because both failures are silent on a host nobody has deployed yet: a
 * `dist/` that does not exist means the emit ran before (or instead of) the build, and a missing
 * `index.html` means the rewrite points at a file the exporter never produced — which is a 404 with extra
 * steps.
 *
 * @param {string} distDir the finished build directory
 * @returns {string} the path written
 */
export function writeRedirects(distDir) {
  const dir = resolve(distDir)
  if (!existsSync(join(dir, 'index.html'))) {
    throw new Error(
      `${dir} has no index.html — the SPA fallback would rewrite every unknown path to a file that ` +
        'does not exist. Run this after the exporter, over its output directory.',
    )
  }
  const path = join(dir, REDIRECTS_FILE)
  writeFileSync(path, REDIRECTS)
  // Read back: the one claim this file makes is that a host will find the rule, so it is checked on the
  // bytes rather than on the string that was passed to `writeFileSync`.
  if (!readFileSync(path, 'utf8').includes(SPA_FALLBACK_RULE)) {
    throw new Error(`${path} was written without its rule`)
  }
  return path
}

// ── CLI ────────────────────────────────────────────────────────────────────────────────────────────
//
// Invoked from each app's `build:web` (see their `package.json`) rather than from the two twin
// `scripts/build-web.mjs` files, so the step is declared once per app in the place a reader looks up what
// `build:web` does, and neither twin has to grow a copy of it.
if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const target = process.argv[2]
  if (target === undefined) {
    console.error('usage: node scripts/pwa/redirects.mjs <distDir>')
    process.exit(1)
  }
  console.log(`✓ ${writeRedirects(target)} — \`${SPA_FALLBACK_RULE}\``)
}
