// Assembles the OpenAPI 3.1 document from the wire schemas. This is the artefact a native repo
// generates its models from (WP3-3), so it is committed and `git diff --exit-code` gated: a stale
// generator is then a red CI rather than a silently divergent iOS client.
//
// There is no `zod-to-openapi` here on purpose. OpenAPI 3.1's Schema Object *is* JSON Schema draft
// 2020-12, which Zod 4 emits natively, so the only thing left to do is the paths/components
// scaffolding below — and one generator fewer to keep in step.

import { z } from 'zod'
import { WIRE_JSON_SCHEMA_OPTIONS } from './json-schema'
// Importing the module (not just `WIRE_ENDPOINTS`) is what registers every shape it reaches —
// including `ErrorResponseSchema`, which appears below only as a `$ref` string.
import { ERROR_CODES, WIRE_ENDPOINTS } from './wire/responses'

/**
 * Bumped only for a **breaking** change, alongside the `oasdiff` gate and an ADR (ADR-052 §5).
 * Additive-optional changes are free and must not touch this.
 */
export const CONTRACT_VERSION = '1.0.0'

/**
 * The documented failure statuses, derived from `ERROR_CODES` so the OpenAPI document cannot list
 * a status the taxonomy doesn't mint — or omit one it does. The previous hand-written `400/404/502`
 * map is exactly how `504` and `500` went undocumented (ADR-064).
 */
const ERROR_RESPONSES: Record<string, unknown> = Object.fromEntries(
  Object.entries(ERROR_CODES).map(([code, { status, retryable }]) => [
    String(status),
    {
      description: `\`code: "${code}"\` — ${retryable ? 'the identical request may succeed later.' : 'permanently wrong; a background client should prune the request, not retry it.'}`,
      content: { 'application/json': { schema: { $ref: '#/components/schemas/ErrorResponse' } } },
    },
  ]),
)

/**
 * Emit every registered wire schema as OpenAPI components.
 *
 * Registry mode only sees schemas whose module has actually been imported, which is why this file
 * imports through `./wire/responses` — that reaches every shape transitively. A schema that no
 * endpoint can return is a schema no client needs.
 */
function components(): Record<string, unknown> {
  const emitted = z.toJSONSchema(z.globalRegistry, {
    ...WIRE_JSON_SCHEMA_OPTIONS,
    uri: (id: string) => `#/components/schemas/${id}`,
  } as never) as { schemas: Record<string, Record<string, unknown>> }

  // `$schema` is meaningful for a standalone JSON Schema document and noise inside an OpenAPI
  // components map, where the dialect is declared once by `jsonSchemaDialect`.
  for (const schema of Object.values(emitted.schemas)) delete schema.$schema
  return emitted.schemas
}

export function buildOpenApiDocument(): Record<string, unknown> {
  const paths: Record<string, unknown> = {}

  for (const ep of WIRE_ENDPOINTS) {
    const responseId = ep.response.meta()?.id
    if (!responseId) {
      // Would silently emit an inline, un-referencable response body — i.e. a component a
      // generator gives an autogenerated name to, which then churns on every unrelated edit.
      throw new Error(`${ep.operationId}: response schema is missing .meta({ id })`)
    }

    paths[ep.path] = {
      get: {
        operationId: ep.operationId,
        summary: ep.summary,
        parameters: ep.params.map((p) => ({
          name: p.name,
          in: p.in,
          required: p.required,
          description: p.description,
          schema: { type: p.type },
        })),
        responses: {
          '200': {
            description: ep.summary,
            content: {
              'application/json': { schema: { $ref: `#/components/schemas/${responseId}` } },
            },
          },
          ...ERROR_RESPONSES,
        },
      },
    }
  }

  return {
    openapi: '3.1.0',
    jsonSchemaDialect: 'https://json-schema.org/draft/2020-12/schema',
    info: {
      title: 'NextBus HK — wire API',
      version: CONTRACT_VERSION,
      description: [
        'Hong Kong bus arrival times, normalized across KMB/LWB, Citybus and Green Minibus.',
        '',
        'Conventions that are easy to get wrong, and are stated per-field in the schemas:',
        '',
        '- **Timestamps** are ISO-8601 with a `+08:00` offset.',
        '- **`"HH:mm"` may exceed 24** — `"25:35"` means 01:35 the next day.',
        '- **Fares are decimal strings.** Compare numerically, display verbatim, never parse to a float.',
        '- **Objects are open.** Additional properties are permitted by design, so a client generated',
        '  from an older revision of this document keeps decoding after a field is added. Do not',
        '  configure your generator to reject unknown keys.',
        '- **Enums marked `x-unknown-tolerant`** will gain members without a major version bump.',
        '  Generate a fallback case (`case unknown(String)`); do not throw on an unrecognized value.',
        '- **ETAs are approximations.** Do not run a per-second countdown; refresh the value only when',
        '  a new reading arrives, and use `observedAt` to show staleness.',
        '- **Every failure returns `ErrorResponse`.** Branch on `code`, and let `retryable` decide',
        '  whether a background client (Widget, complication) retries or prunes the request. The',
        '  status code always agrees with `code`. `error` duplicates `message` and is deprecated.',
      ].join('\n'),
    },
    paths,
    components: { schemas: components() },
  }
}
