/** @vitest-environment jsdom */
// The clock a subscription-fed screen runs on, and the honesty cue that depends on it.
//
// WHY THIS FILE EXISTS
// `refetchInterval` did two jobs. It fetched, and it **re-rendered** — and `const now = Date.now()` in a
// screen body only advances when something re-renders it. WP5-0 deleted the interval and took the clock
// with it: a round in which nothing changed calls no listener (deliberately — ADR-008), `useClientPolicy`
// has a `staleTime` and no interval, and `refetchOnWindowFocus` is `false`. So on a quiet stop nothing
// re-rendered, and `etaReadout`'s `stale` flag — the one cue that says *"these times have stopped
// arriving"* — could never fire. The screen went on showing confident minutes against a frozen clock.
//
// That is the failure this pins, and it is worth being precise about which half is the bug. The **label**
// ageing on a coarse cadence is what riders have seen since v1 and is not the countdown ADR-008 forbids —
// that rule bans fabricated precision, not arithmetic on a timestamp we were given. The **stale flag never
// firing** is the honesty regression, and the two share one mechanism: a `now` that moves.
//
// Deliberately not the seam-substitution harness next door. That one pins the *frames* and pins `now` to a
// constant so two engines can be compared byte for byte; a frozen clock is the right choice there and the
// reason it could never have caught this. Here the clock is the subject.

import { CLIENT_POLICY_DEFAULTS, type Eta, etaReadout, resolveClientPolicy } from '@nextbus/core'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { act } from 'react'
import { createRoot } from 'react-dom/client'
import { View } from 'react-native'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { Text } from '../components/Text'
import { useLiveEtas } from '../lib/useLiveEtas'

const STOP_ID = 'KMB:A1B2C3'
const ROUTE_1 = 'KMB:1:outbound:1'
const POLICY = resolveClientPolicy(undefined)

/** 2026-07-30 10:00:00 +08:00, the instant every assertion below is relative to. */
const T0 = Date.parse('2026-07-30T02:00:00.000Z')

/**
 * One reading, generated by the operator half a minute before `T0` and arriving four minutes out.
 *
 * `dataTimestamp` is the field `isStale` ages against — not `observedAt`, which nothing reads (recorded in
 * WP5-1). So this reading becomes stale at `T0 + staleAfterMs - 30 s`, i.e. 60 s in.
 */
const READING: Eta = {
  routeId: ROUTE_1,
  stopId: STOP_ID,
  operator: 'KMB',
  arrivals: ['2026-07-30T10:04:00+08:00'],
  dataTimestamp: '2026-07-30T09:59:30+08:00',
  observedAt: '2026-07-30T01:59:30.000Z',
}

/**
 * A source that answers the initial fetch and then **says nothing, ever** — the quiet stop.
 *
 * This is not a degenerate fixture: it is what both engines do when upstream has not republished. The poll
 * emulator sends a `delta` only for a reading that changed, and the shard it emulates sends no frame at all.
 * A fake that helpfully re-delivered the same reading on a cadence would repaint the screen and hide the
 * very thing under test.
 */
function silentSource() {
  return {
    watch: () => ({ unsubscribe: () => {} }),
  } as unknown as Parameters<typeof useLiveEtas>[1] extends { source?: infer S } ? S : never
}

/**
 * The row as the Place screen renders it: the readout computed against the hook's `now`, with `stale`
 * projected into text so it can be read back. `EtaBadge` renders staleness as opacity, which is a style
 * decision and correctly the renderer's — so the test asserts on the *kernel's* verdict reaching the render,
 * which is the part that stopped working, rather than on a class name that could change for cosmetic reasons.
 */
/** Renders of `Row`, for the cadence assertion — a cadence is not observable in the label. */
let renders = 0

function Row({ refreshAfterMs }: { refreshAfterMs: number }) {
  renders += 1
  const { now } = useLiveEtas(STOP_ID, { source: silentSource(), refreshAfterMs })
  const readout = etaReadout(READING, 'en', now, POLICY)
  const label = readout.label.kind === 'mins' ? `${readout.label.value} min` : readout.label.kind
  return (
    <View>
      <Text variant="body">{label}</Text>
      <Text variant="body">{readout.stale ? 'stale' : 'fresh'}</Text>
    </View>
  )
}

function visibleText(host: HTMLElement): string[] {
  const walker = document.createTreeWalker(host, NodeFilter.SHOW_TEXT)
  const out: string[] = []
  let node = walker.nextNode()
  while (node) {
    const text = (node.textContent ?? '').trim()
    if (text) out.push(text)
    node = walker.nextNode()
  }
  return out
}

let root: ReturnType<typeof createRoot> | null = null

beforeEach(() => {
  vi.useFakeTimers()
  vi.setSystemTime(T0)
})

afterEach(async () => {
  if (root) await act(async () => root?.unmount())
  root = null
  vi.useRealTimers()
})

async function mount(refreshAfterMs: number): Promise<HTMLElement> {
  document.body.innerHTML = '<div id="host"></div>'
  const host = document.getElementById('host')
  if (!host) throw new Error('unreachable: the host div was just written')
  const queryClient = new QueryClient({ defaultOptions: { queries: { retry: false } } })
  root = createRoot(host)
  await act(async () => {
    root?.render(
      <QueryClientProvider client={queryClient}>
        <Row refreshAfterMs={refreshAfterMs} />
      </QueryClientProvider>,
    )
  })
  return host
}

describe('a subscription-fed screen still has a clock', () => {
  it('ages the arrival and raises the stale cue with no new data at all', async () => {
    const host = await mount(POLICY.refreshAfterMs)
    expect(visibleText(host)).toEqual(['4 min', 'fresh'])

    // One cadence in: 210 s to the arrival, and the reading is 60 s old — inside the band.
    await act(async () => {
      await vi.advanceTimersByTimeAsync(POLICY.refreshAfterMs)
    })
    expect(visibleText(host)).toEqual(['3 min', 'fresh'])

    // Two cadences: 90 s old, which **used to be the boundary and is now comfortably inside the band**
    // (ADR-122 raised `staleAfterMs` to 120 s, because 90 fired on healthy Citybus data that arrives up to
    // 105 s old). Kept as a step rather than deleted: it is the age at which this cue used to appear, so a
    // port that hard-coded 90 fails here rather than somewhere vaguer.
    await act(async () => {
      await vi.advanceTimersByTimeAsync(POLICY.refreshAfterMs)
    })
    expect(visibleText(host)).toEqual(['3 min', 'fresh'])

    // Three cadences: exactly 120 s old. `isStale` is `now - dataTimestamp > staleAfterMs`, strictly
    // greater, so the boundary itself is still fresh. Asserted rather than glossed, because "at the
    // threshold" is the row a hand-port gets wrong.
    await act(async () => {
      await vi.advanceTimersByTimeAsync(POLICY.refreshAfterMs)
    })
    expect(visibleText(host)).toEqual(['2 min', 'fresh'])

    // Four cadences: 150 s old, and the cue lands. **This is the assertion that fails against a frozen
    // clock** — without the tick the screen still reads `4 min` / `fresh` here: two and a half minutes after
    // the last reading arrived, thirty seconds before the bus is due, and no hint that anything has stopped.
    await act(async () => {
      await vi.advanceTimersByTimeAsync(POLICY.refreshAfterMs)
    })
    expect(visibleText(host)).toEqual(['2 min', 'stale'])
  })

  it('ticks on the served cadence rather than a cadence of its own', async () => {
    // The served number governs how long a rider can look at a dead screen before it admits it, so the tick
    // must *be* that number. A literal here would be the fourth value in ADR-053's disagreement, one layer
    // below the three it already found — and a cadence cannot be read off the rendered label, because the
    // label only changes each 60 s of arrival ageing however often it is recomputed. So this counts renders.
    const served = 5_000
    expect(served).not.toBe(CLIENT_POLICY_DEFAULTS.refreshAfterMs)
    renders = 0
    await mount(served)
    const atMount = renders
    expect(atMount).toBeGreaterThan(0)

    await act(async () => {
      await vi.advanceTimersByTimeAsync(served - 1)
    })
    expect(renders).toBe(atMount)

    await act(async () => {
      await vi.advanceTimersByTimeAsync(1)
    })
    expect(renders).toBe(atMount + 1)

    // One cadence at a time, rather than three at once: React batches state updates that land inside a
    // single `act`, so advancing 3× the interval in one step legitimately produces fewer than three renders.
    // Asserting per-tick measures the cadence; asserting the batch would measure React's scheduler.
    for (let tick = 2; tick <= 4; tick += 1) {
      await act(async () => {
        await vi.advanceTimersByTimeAsync(served)
      })
      expect(renders).toBe(atMount + tick)
    }
  })
})
